%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% example script to generate simulated interacting brain regions and
% perform Current-Based Decomposition (CURBD). Ref:
%
% Perich MG et al. Inferring brain-wide interactions using data-constrained
% recurrent neural network models. bioRxiv. DOI:
%
% Written by Matthew G. Perich. Updated December 2020.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

sim = threeRegionSim();

activity = cat(1,sim.Ra,sim.Rb,sim.Rc);
regions = { ...
    'Region A',1:sim.params.Na; ...
    'Region B',sim.params.Na+1:sim.params.Na+sim.params.Nb; ...
    'Region C',sim.params.Na+sim.params.Nb+1:sim.params.Na+sim.params.Nb+sim.params.Nc; ...
    };

model = trainMultiRegionRNN(activity, struct( ...
    'dtData',sim.params.dtData, ...
    'dtFactor',10, ...
    'trainType','currents', ...
    'regionNames',{regions(:,1)}, ...
    'regionIDs',{regions(:,2)}, ...
    'tauRNN',2*sim.params.tau, ...
    'nRuns',100, ...
    'nFree',5));

CURBD = computeCURBD(model);